"""empty message

Revision ID: 32f5d043bdaf
Revises: 6a26e7d5422d
Create Date: 2021-04-25 13:44:10.530234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f5d043bdaf'
down_revision = '6a26e7d5422d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('starships', sa.Column('description', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('starships', 'description')
    # ### end Alembic commands ###
