"""empty message

Revision ID: 6a26e7d5422d
Revises: 97736d8bad3f
Create Date: 2021-04-25 13:39:38.540006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a26e7d5422d'
down_revision = '97736d8bad3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('description', sa.String(length=800), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'description')
    # ### end Alembic commands ###
