"""empty message

Revision ID: 740187a71006
Revises: 70dbb73f3c1a
Create Date: 2021-04-21 16:03:12.187162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '740187a71006'
down_revision = '70dbb73f3c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld_id', sa.Integer(), nullable=True))
    op.drop_constraint('people_ibfk_1', 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'planets', ['homeworld_id'], ['id'])
    op.drop_column('people', 'homeworld')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('homeworld', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key('people_ibfk_1', 'people', 'planets', ['homeworld'], ['id'])
    op.drop_column('people', 'homeworld_id')
    # ### end Alembic commands ###
