"""empty message

Revision ID: 97736d8bad3f
Revises: 4d60ade4f0f4
Create Date: 2021-04-25 13:29:24.511418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97736d8bad3f'
down_revision = '4d60ade4f0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'description')
    # ### end Alembic commands ###
