"""empty message

Revision ID: a88e97ff5a59
Revises: 74a5582ccae0
Create Date: 2021-04-21 12:18:40.449412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a88e97ff5a59'
down_revision = '74a5582ccae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_people', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_people', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_planets', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_planets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_starships', 'starships_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_starships', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_starships', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_starships', 'starships_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_planets', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_planets', 'planets_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_people', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_people', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
