"""empty message

Revision ID: f42bc33a02bb
Revises: 5a984bf5480f
Create Date: 2021-04-24 15:49:28.868307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42bc33a02bb'
down_revision = '5a984bf5480f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('photo_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'photo_url')
    # ### end Alembic commands ###
